services:
    endroid.qrcode.twig.extension:
        class: Endroid\Bundle\QrCodeBundle\Twig\Extension\QrCodeExtension
        arguments: [  ]
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [ @service_container ] ]
